### ISSUE TITLE
Adding new sites and mirrors to the list

### ISSUE THREAD

**Issue by pavel-manylov-meduza** [babolivier/rsf-censorship-detector#2]
Reporters Without Borders created a mirror for meduza.io available at  https://meduza.global.ssl.fastly.net/ . Here is an official news from RSF: https://rsf.org/en/news/rsf-creates-mirror-leading-russian-exile-news-site-blocked-kremlin .

Can you  please add this mirror to the plugin? 
What is the correct way to notify about new mirrors available?

**Comment by babolivier** [comment]
> Can you please add this mirror to the plugin?

The list of mirrors is automatically retrieved from RSF's official repository here: https://github.com/RSF-RWB/collateralfreedom/blob/master/sites.json - that way the extension doesn't have to be updated for each new mirror.

There are currently some bugs with the extension (due to it not having been updated in a while). I've pushed fixes to this repository a few minutes ago and will package it up to send it to Mozilla's and Google's stores later today.

>  What is the correct way to notify about new mirrors available?

There currently isn't any notification mechanism in the extension. The only way to discover whether a mirror exists for a website is to try to visit it and see if the extension's icon turns red (at least when the fixed versions of the extension will be able on the stores).
